### ISSUE TITLE
singlestoredb.exceptions.OperationsError 1046: In order to use shared tier you need to select a database by default

### ISSUE THREAD

**Issue by jimitnaik** [ayushpai/RAG-SingleStore-ChatBot#1]
I am trying to create an RAG Chatbot and I am facing an error mentioned in the title for line 11 in RAG_ChatBot.py script.

Could you please help debug this error?

**Comment by ayushpai** [comment]
You need to create a database in your SingleStore workspace. The URL should include the database name.

Here is how it should be formatted:

"username:password@server:port/database"

**Comment by ayushpai** [comment]
You need to create a database in your SingleStore workspace. The URL should include the database name.

Here is how it should be formatted:

"username:password@server:port/database"

**Comment by ayushpai** [comment]
You need to create a database in your SingleStore workspace. The URL should include the database name.

Here is how it should be formatted:

"username:password@server:port/database"
